/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JOptionPane;
import java.sql.*;
import ConexaoBanco.ModuloConexao;

/**
 *
 * @author walde
 */
public class Telalogin extends javax.swing.JFrame {
    //usando a variavel conexao
    Connection conexao = null;
    //criando variaveis especiais para conexao com o banco de dados
    //PreparedStatement e ResultSet são frameworks do pacote java.sql
    //e servem para preparar e executar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    //criando o metodo logar
    public void logar(){
        String sql = "select * from tbusuario where login=? and senha=?";
        try {
            //as linhas abaixo preparam a consulta ao banco em funçao do 
            //que foi digitado nas caixas de texto. o ? é substituido pelo 
            //valor das variaveis
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuario.getText());
            pst.setString(2, txtSenha.getText());
            //a linha abaixo executa a query
            rs = pst.executeQuery();
            
            //se existir usuario e senha correspondente
            if (rs.next()){
                //a linha abaixo obtem o conteudo do campo perfil
                //String perfil=rs.getString(5);
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
                this.dispose();
                conexao.close();                                 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form Telalogin
     */
    public Telalogin() {
        initComponents();
        //estabelecer a conexão com o banco sempre neste ponto
        conexao = ModuloConexao.conector();
        if (conexao != null){
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bancook.png")));
        }else {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bancoerror.png")));
        }
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabelLogo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Acessar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 170, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 170, 80, 30);

        jLabelUsuario.setFont(jLabelUsuario.getFont().deriveFont(jLabelUsuario.getFont().getStyle() | java.awt.Font.BOLD, jLabelUsuario.getFont().getSize()+1));
        jLabelUsuario.setText("Usuáro:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(240, 50, 60, 30);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(290, 50, 170, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(240, 120, 50, 15);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(290, 110, 170, 30);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_1.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(10, 10, 210, 130);

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bancoerror.png"))); // NOI18N
        getContentPane().add(lblStatus);
        lblStatus.setBounds(10, 190, 32, 40);

        lblFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoInternoFrame.jpg"))); // NOI18N
        getContentPane().add(lblFundoLogin);
        lblFundoLogin.setBounds(0, 0, 480, 240);

        setSize(new java.awt.Dimension(499, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    /*if(txtUsuario.getText().equals("admin")&& txtSenha.getText().equals("1234")){
    TelaPrincipal tela = new TelaPrincipal();
    tela.setVisible(true);
    dispose();
    } else{
        JOptionPane.showMessageDialog(rootPane, "Senha ou Usuario Invalido");
    }*/
        logar();
    }//GEN-LAST:event_jButton1ActionPerformed
      
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telalogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel lblFundoLogin;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
