/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JInternalFrame;

/**
 *
 * @author walde
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemvindo = new javax.swing.JInternalFrame();
        jPanelInernal = new javax.swing.JPanel();
        jLabelPainelCadastro = new javax.swing.JLabel();
        jButtonCadNFe = new javax.swing.JButton();
        jButtonCadEmpresas = new javax.swing.JButton();
        jButtonCadSecretarias = new javax.swing.JButton();
        jButtonRelDespacho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelPanelFundo = new javax.swing.JLabel();
        jLabelApresentação = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFundointernal = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadEmpresas = new javax.swing.JMenuItem();
        jMenuItemCadSecretarias = new javax.swing.JMenuItem();
        jMenuItemCadNotasFiscais = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuDespachos = new javax.swing.JMenu();
        jMenuItemFinanceiro = new javax.swing.JMenuItem();
        jMenuItemFundos = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBenvindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemvindo.setBackground(new java.awt.Color(204, 204, 204));
        jInternalFrameBemvindo.setBorder(new javax.swing.border.MatteBorder(null));
        jInternalFrameBemvindo.setClosable(true);
        jInternalFrameBemvindo.setTitle("Bem - Vindo !!");
        jInternalFrameBemvindo.setToolTipText("");
        jInternalFrameBemvindo.setVisible(true);
        jInternalFrameBemvindo.getContentPane().setLayout(null);

        jPanelInernal.setBackground(new java.awt.Color(255, 239, 238));
        jPanelInernal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInernal.setLayout(null);

        jLabelPainelCadastro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPainelCadastro.setText("Cadastro de :");
        jPanelInernal.add(jLabelPainelCadastro);
        jLabelPainelCadastro.setBounds(20, 20, 140, 30);

        jButtonCadNFe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IcoNF.png"))); // NOI18N
        jButtonCadNFe.setToolTipText("Notas Fiscais");
        jPanelInernal.add(jButtonCadNFe);
        jButtonCadNFe.setBounds(260, 60, 110, 110);

        jButtonCadEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IcoEmp.png"))); // NOI18N
        jButtonCadEmpresas.setToolTipText("Empresas");
        jPanelInernal.add(jButtonCadEmpresas);
        jButtonCadEmpresas.setBounds(20, 60, 110, 110);

        jButtonCadSecretarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SECRETARIAS.png"))); // NOI18N
        jButtonCadSecretarias.setToolTipText("Secretarias");
        jPanelInernal.add(jButtonCadSecretarias);
        jButtonCadSecretarias.setBounds(140, 60, 110, 110);

        jButtonRelDespacho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DESPACHOS.png"))); // NOI18N
        jPanelInernal.add(jButtonRelDespacho);
        jButtonRelDespacho.setBounds(20, 210, 110, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Relatórios de:");
        jPanelInernal.add(jLabel1);
        jLabel1.setBounds(20, 180, 130, 22);

        jLabelPanelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaengrenage.png"))); // NOI18N
        jPanelInernal.add(jLabelPanelFundo);
        jLabelPanelFundo.setBounds(10, 10, 800, 310);

        jInternalFrameBemvindo.getContentPane().add(jPanelInernal);
        jPanelInernal.setBounds(100, 130, 820, 330);

        jLabelApresentação.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelApresentação.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemvindo.getContentPane().add(jLabelApresentação);
        jLabelApresentação.setBounds(350, 50, 570, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_1.png"))); // NOI18N
        jInternalFrameBemvindo.getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 0, 210, 130);

        lblFundointernal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoInternoFrame.jpg"))); // NOI18N
        jInternalFrameBemvindo.getContentPane().add(lblFundointernal);
        lblFundointernal.setBounds(0, 0, 980, 470);

        getContentPane().add(jInternalFrameBemvindo);
        jInternalFrameBemvindo.setBounds(90, 30, 980, 500);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(-6, 0, 1110, 540);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadEmpresas.setText("Empresas");
        jMenuItemCadEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEmpresasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadEmpresas);

        jMenuItemCadSecretarias.setText("Secretarias");
        jMenuCadastro.add(jMenuItemCadSecretarias);

        jMenuItemCadNotasFiscais.setText("Notas Fiscal");
        jMenuCadastro.add(jMenuItemCadNotasFiscais);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorio.setText("Relatório");

        jMenuDespachos.setText("Despachos");

        jMenuItemFinanceiro.setText("Financeiro");
        jMenuDespachos.add(jMenuItemFinanceiro);

        jMenuItemFundos.setText("Fundos");
        jMenuDespachos.add(jMenuItemFundos);

        jMenuRelatorio.add(jMenuDespachos);

        jMenuBar1.add(jMenuRelatorio);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBenvindo.setText("Tela Bem vindos");
        jMenuItemTelaBenvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBenvindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBenvindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1120, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEmpresasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadEmpresasActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBenvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBenvindoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemTelaBenvindoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadEmpresas;
    private javax.swing.JButton jButtonCadNFe;
    private javax.swing.JButton jButtonCadSecretarias;
    private javax.swing.JButton jButtonRelDespacho;
    private javax.swing.JInternalFrame jInternalFrameBemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApresentação;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelCadastro;
    private javax.swing.JLabel jLabelPanelFundo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuDespachos;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadEmpresas;
    private javax.swing.JMenuItem jMenuItemCadNotasFiscais;
    private javax.swing.JMenuItem jMenuItemCadSecretarias;
    private javax.swing.JMenuItem jMenuItemFinanceiro;
    private javax.swing.JMenuItem jMenuItemFundos;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBenvindo;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInernal;
    private javax.swing.JLabel lblFundointernal;
    // End of variables declaration//GEN-END:variables
}
